# Generated by Django 3.2.6 on 2021-09-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Категории товаров',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Параметры',
                'db_table': 'Params',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.category')),
            ],
            options={
                'verbose_name': 'Товары',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProdParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, verbose_name='Значение параметра')),
                ('comments', models.TextField(blank=True, verbose_name='Примечание')),
                ('param_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.params')),
                ('prod_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.products')),
            ],
            options={
                'verbose_name': 'Параметры товара',
                'db_table': 'ProdParams',
            },
        ),
    ]
