# Generated by Django 3.2.6 on 2021-09-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('comments', models.TextField(verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Параметры товаров',
                'db_table': 'Params',
            },
        ),
        migrations.CreateModel(
            name='ProdParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, verbose_name='Значение параметра')),
                ('comments', models.TextField(verbose_name='Примечание')),
                ('param_name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.params')),
            ],
            options={
                'verbose_name': 'Параметры товара',
                'db_table': 'ProdParams',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, upload_to='product_images')),
                ('comments', models.TextField(verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Товары',
                'db_table': 'Products',
            },
        ),
        migrations.DeleteModel(
            name='ProdGroup',
        ),
        migrations.AddField(
            model_name='prodparams',
            name='prod_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='mainapp.products'),
        ),
    ]
