# Generated by Django 3.2.6 on 2021-09-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='sex',
            field=models.CharField(blank=True, max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='email',
            field=models.CharField(blank=True, max_length=60, verbose_name='e-mail'),
        ),
    ]
